### ISSUE TITLE
Aplicação de filtro de polígonos por data de classificação

### ISSUE THREAD

**Issue by gracielle-ch** [brazil-data-cube/forest-monitor-app#35]
Filtro parecido ao que tem para pesquisar as imagens de satélite. Filtro para mostrar apenas os polígonos classificados em datas que é preciso realizar alguma análise específica, deixando os outros polígonos ocultos temporariamente.

**Comment by claudiobogossian** [comment]
This feature has to be discussed a little bit more, the meeting about it will run on 31/07/2020.  This filter should filter only Deter Layer polygons.
